---
- name: Upload le .deb de batctl
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: /tmp/{{ item }}
      mode: "0644"
  loop:
      - batctl_2020.4-2_arm64.deb
      - vim-common_8.2.2434-3+deb11u1_all.deb
      - vim-runtime_8.2.2434-3+deb11u1_all.deb
      - vim_8.2.2434-3+deb11u1_arm64.deb

- name: Installer batctl et modules nécessaires
  ansible.builtin.apt:
      deb: /tmp/{{ item }}
      state: present
  loop:
      - batctl_2020.4-2_arm64.deb
      - vim-common_8.2.2434-3+deb11u1_all.deb
      - vim-runtime_8.2.2434-3+deb11u1_all.deb
      - vim_8.2.2434-3+deb11u1_arm64.deb
