---
- name: Ajoute batman-adv au kernel
  community.general.modprobe:
      name: batman-adv
      state: present

- name: Empeche le DHCP de gérer l'interface wlan0
  ansible.builtin.lineinfile:
      path: /etc/dhcpcd.conf
      line: "{{ item }}"
      state: present
      create: true
      mode: "0644"
  loop:
      - denyinterfaces wlan0

- name: Batman au boot
  ansible.builtin.lineinfile:
      path: /etc/modules
      line: "batman-adv"
      state: present
      create: true
      mode: "0644"

- name: Upload les fichiers network
  ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/etc/network/interfaces.d/{{ item }}"
      mode: "0644"
  loop:
      - eth0
      - bat0
      - wlan0

- name: NetworkManager gère pas ifupdown
  ansible.builtin.replace:
      path: /etc/NetworkManager/NetworkManager.conf
      regexp: "managed=true"
      replace: "managed=false"

- name: Désactive NetworkManager
  ansible.builtin.systemd:
      name: NetworkManager
      state: stopped
      enabled: false

- name: Upload le script de démarrage
  ansible.builtin.copy:
      src: batman-startup.sh
      dest: /root/batman-startup.sh
      mode: "0755"

- name: Démarre batman au boot
  ansible.builtin.cron:
      name: "batman"
      job: "/root/batman-startup.sh > /dev/null"
      user: root
      special_time: reboot
      state: present
