---
- name: Ajoute batman-adv au kernel
  community.general.modprobe:
      name: batman-adv
      state: present

- name: Batman au boot
  ansible.builtin.lineinfile:
      path: /etc/modules
      line: "batman-adv"
      state: present
      create: true
      mode: "0644"

- name: Empeche le DHCP de gérer l'interface wlan0
  ansible.builtin.lineinfile:
      path: /etc/dhcpcd.conf
      line: "{{ item }}"
      state: present
      create: true
      mode: "0644"
  loop:
      - denyinterfaces wlan0

- name: Upload les fichiers network
  ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/etc/network/interfaces.d/{{ item }}"
      mode: "0644"
  loop:
      - eth0
      - wlan0
      - bat0

- name: Upload le script de démarrage
  ansible.builtin.copy:
      src: batman-startup.sh
      dest: /root/batman-startup.sh
      mode: "0755"
  when: "master is not defined or master == 'false'"

- name: Démarre batman au boot
  ansible.builtin.cron:
      name: "batman"
      job: "/root/batman-startup.sh > /dev/null"
      user: root
      special_time: reboot
      state: present
  when: "master is not defined or master == 'false'"

- name: Upload le fichier network batman
  ansible.builtin.template:
      src: "bat0-routeur.j2"
      dest: "/etc/network/interfaces.d/bat0"
      mode: "0644"
  when: "master is defined and master == 'true'"

- name: Make a it server
  ansible.builtin.import_tasks:
      file: server.yml
  when: "master is defined and master == 'true'"
