---
- name: Enable and persist ip forwarding
  ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: true
      reload: true

- name: Upload le script serveur
  ansible.builtin.copy:
      src: batman-routeur.sh
      dest: /root/batman-routeur.sh
      mode: "0755"

- name: Démarre batman au boot
  ansible.builtin.cron:
      name: "batman-routeur"
      job: "/root/batman-routeur.sh > /dev/null"
      user: root
      special_time: reboot
      state: present
